# Generated by Django 4.2.3 on 2023-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_myuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nip',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
