# Generated by Django 4.2.3 on 2023-08-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'during'), (3, 'rejected'), (4, 'done')], default=1),
        ),
    ]
