# Generated by Django 4.2.3 on 2023-08-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='company',
        ),
    ]
