# Generated by Django 4.2.3 on 2023-08-01 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_status_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 16, 48, 10, 433938)),
        ),
        migrations.AddField(
            model_name='order',
            name='modyfication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 16, 48, 10, 433954)),
        ),
    ]
