# Generated by Django 4.2.3 on 2023-08-01 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_order_creation_date_order_modyfication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 16, 48, 22, 189868)),
        ),
        migrations.AlterField(
            model_name='order',
            name='modyfication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 16, 48, 22, 189883)),
        ),
    ]
