# Generated by Django 4.2.3 on 2023-08-01 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_order_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='modyfication_date',
        ),
        migrations.AddField(
            model_name='order',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 16, 49, 17, 286420)),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 16, 49, 17, 286404)),
        ),
    ]
