# Generated by Django 4.2.3 on 2023-08-01 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_remove_order_modyfication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 17, 10, 12, 535710)),
        ),
        migrations.AlterField(
            model_name='order',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 17, 10, 12, 535726)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complaints.status'),
        ),
    ]
