# Generated by Django 4.2.3 on 2023-08-01 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_alter_order_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 17, 13, 23, 49379)),
        ),
        migrations.AlterField(
            model_name='order',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 17, 13, 23, 49395)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'during'), (3, 'rejected'), (4, 'done')], default=1),
        ),
    ]
