# Generated by Django 4.2.3 on 2023-08-01 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_alter_order_creation_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 17, 15, 4, 417744)),
        ),
        migrations.AlterField(
            model_name='order',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 17, 15, 4, 417759)),
        ),
    ]
